apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-jenkins-webapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: spring-jenkins-webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-jenkins-webapp
    spec:
      containers:
        - name: spring-jenkins-webapp
          image: lowdisk17/springjenkinswebapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888


---

apiVersion: v1
kind: Service
metadata:
  name: springjenkinswebapp
  namespace: dev
spec:
  selector:
    app: spring-jenkins-webapp
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
  type: NodePort